services:
  validator:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
      args:
        TORCH_CUDA_ARCH_LIST: "7.5 8.0 8.6+PTX"  # Optimized CUDA architectures
    command: ["api"]
    user: sandbox
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: sandbox_data
        target: /sandbox/data
      - type: volume
        source: numba_cache
        target: /tmp/numba_cache
      - type: volume
        source: hf_cache
        target: /sandbox/.cache/huggingface
      - type: volume
        source: models_cache
        target: /sandbox/models
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 24G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute,utility]
              count: 1
              options:
                memory.limit: 16G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - HF_HOME=/sandbox/.cache/huggingface
      - TORCH_HOME=/sandbox/.cache/torch
      - TRANSFORMERS_CACHE=/sandbox/.cache/huggingface/transformers
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - OMP_NUM_THREADS=4
      - CUDA_LAUNCH_BLOCKING=0
      - VALIDATOR_MODEL_ID=${VALIDATOR_MODEL_ID:-tezuesh/moshi_general}
      - VALIDATOR_MODEL_REVISION=${VALIDATOR_MODEL_REVISION:-main}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_NICE  # Allow process priority management
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - validator_net
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    stop_grace_period: 120s
    restart: unless-stopped

networks:
  validator_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  sandbox_data:
    driver: local
    driver_opts:
      type: none
      device: /sandbox/data
      o: bind
  numba_cache:
    driver: local
  hf_cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=20G"
  models_cache:
    driver: local